title: Emby Server Documentation
description: User Documentation for Emby Server
show_downloads: false
git_branch: master
logo_url: https://emby.media/resources/logowhite_1881.png
google_analytics:
custom_head: false
custom_sidebar: false
custom_footer: false
service: github
search_engine : "js"
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
