title: Emby Server Documentation
description: User Documentation for Emby Server
show_downloads: false
git_branch: master
logo_url: https://emby.media/resources/logowhite_1881.png
google_analytics:
wiki_folder: wiki
custom_head: false
custom_sidebar: false
custom_footer: false
markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
